### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by unixhelden** [HarleyDavidson86/gologger#1]
This Library needs a possibility to rotate the Logs either by day or Volume of the log file.

It would be nice if there was an additonal Option to compress logs.
Also delete rotated Logs after X amount of days :)

**Comment by HarleyDavidson86** [comment]
At this time, the library only prints messages to stdout.
Maybe in the future I will implement a feature to write into a file or create a possibility to interact with [the package lumberjack](https://github.com/natefinch/lumberjack)

**Comment by HarleyDavidson86** [comment]
Have a look at v1.0.2 which fullfills you request!
